easy = '''The big, red ball bounced high and low, making a happy sound as it hit the ground. The dog's tail wagged excitedly as it chased after the ball. Its tongue hung out happily as it ran. Children laughed and cheered as the dog tried to catch the ball. Some children were building sandcastles while others were playing tag. Parents sat on benches, watching their kids with smiles on their faces. Ice cream trucks played cheerful music, tempting everyone with sweet treats. The park was filled with the sounds of laughter, barking, and children's chatter. It was a perfect summer day, and everyone seemed to be enjoying themselves.
The sun was shining brightly, warming everyone's skin. A gentle breeze rustled through the trees, providing a cool relief from the heat. People were having picnics on the grass, sharing food and stories. Some brought blankets and lay down to soak up the sun. The park was a peaceful oasis in the busy city. It was a place where people could relax and forget about their worries.
As the day began to wind down, the sun started to set. The sky turned shades of pink and orange, creating a beautiful backdrop. People started to pack up their belongings and head home. Children were tired but happy, their cheeks flushed with excitement. The park slowly emptied, leaving behind a quiet peacefulness. It had been a magical day, filled with joy and laughter.
'''

medium = '''The old, wooden house stood quietly on the edge of town. It had a mysterious aura, with creaky floors and shadowed corners. Inside, strange trinkets and forgotten treasures filled the dusty rooms. A feeling of anticipation grew as I explored the house, wondering what secrets it held. The attic was a labyrinth of shadows, filled with boxes of unknown contents. With a trembling hand, I opened one, revealing a collection of old letters and faded photographs.
The garden was a wild, untamed space, filled with tall grass and colorful wildflowers. A small, winding path led deeper into the overgrown area. As I ventured further, I discovered a hidden bench nestled beneath a sprawling oak tree. The sunlight filtered through the leaves, creating a dappled pattern on the ground. It was a peaceful spot to sit and think, away from the hustle and bustle of everyday life.
Curiosity ignited my spirit as I explored the house and garden. The old house held a certain charm, a sense of history and mystery. With each new discovery, my imagination ran wild. I wondered about the people who had lived there before, their lives, their dreams, and their secrets. The house seemed to whisper stories of the past, inviting me to become a part of its history.
'''

hard = '''Ephemeral vestiges of a bygone era permeate this antiquated edifice, their spectral imprints etched into the very fabric of its dilapidated structure. Obscure artifacts and enigmatic relics are strewn haphazardly throughout the labyrinthine interior, tantalizing the inquisitive mind with promises of arcane knowledge. A palpable aura of desolation hangs heavy in the air, punctuated by the mournful whisperings of forgotten echoes.
Esoteric symbolism adorns the cryptic tapestry, interwoven with arcane motifs that defy rational interpretation. Obscure ciphers and enigmatic hieroglyphs are scattered across the parchment, tantalizing the intellect with promises of profound revelations. The parchment's fragile nature belies the enduring potency of the encoded wisdom it purportedly contains. Intricate patterns and labyrinthine designs converge, forming a visual enigma that defies superficial comprehension.
A cacophony of discordant elements converges within the subterranean chamber, creating an atmosphere of otherworldly dread. Ethereal luminescence emanates from an unknown source, casting grotesque shadows that dance erratically upon the cavernous walls. An acrid scent permeates the air, a noxious amalgam of decay and sulfurous fumes. The subterranean depths teem with unseen entities, their presence palpable yet intangible, inducing a profound sense of unease.
'''